# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file is the device-specific product definition file for
# smdk4x12. It lists all the overlays, files, modules and properties
# that are specific to this hardware: i.e. those are device-specific
# drivers, configuration files, settings, etc...

# Note that smdk4x12 is not a fully open device. Some of the drivers
# aren't publicly available in all circumstances, which means that some
# of the hardware capabilities aren't present in builds where those
# drivers aren't available. Such cases are handled by having this file
# separated into two halves: this half here contains the parts that
# are available to everyone, while another half in the vendor/ hierarchy
# augments that set with the parts that are only relevant when all the
# associated drivers are available. Aspects that are irrelevant but
# harmless in no-driver builds should be kept here for simplicity and
# transparency. There are two variants of the half that deals with
# the unavailable drivers: one is directly checked into the unreleased
# vendor tree and is used by engineers who have access to it. The other
# is generated by setup-makefile.sh in the same directory as this files,
# and is used by people who have access to binary versions of the drivers
# but not to the original vendor tree. Be sure to update both.



# These is the hardware-specific overlay, which points to the location
# of hardware-specific resource overrides, typically the frameworks and
# application settings that are stored in resourced.

LOCAL_PATH := device/samsung/smdk4x12

include $(LOCAL_PATH)/BoardConfig.mk

ifeq ($(BOARD_EMMC_BSP),true)
source_vold_fstab_file := $(LOCAL_PATH)/conf/vold_emmc.fstab
else
source_vold_fstab_file := $(LOCAL_PATH)/conf/vold_sdmmc.fstab
endif

DEVICE_PACKAGE_OVERLAYS := $(LOCAL_PATH)/overlay

# These are the hardware-specific configuration files
PRODUCT_COPY_FILES += \
	$(source_vold_fstab_file):system/etc/vold.fstab

ifeq ($(BOARD_USES_HGL),true)
PRODUCT_COPY_FILES += \
	device/samsung/smdk4x12/conf/egl.cfg:system/lib/egl/egl.cfg \
	device/samsung/exynos4/lib/mali_ump/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
	device/samsung/exynos4/lib/mali_ump/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
	device/samsung/exynos4/lib/mali_ump/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
	device/samsung/exynos4/lib/mali_ump/libMali.so:system/lib/libMali.so \
	device/samsung/exynos4/lib/mali_ump/libMali.so:obj/lib/libMali.so \
	device/samsung/exynos4/lib/mali_ump/libUMP.so:system/lib/libUMP.so \
	device/samsung/exynos4/lib/mali_ump/libUMP.so:obj/lib/libUMP.so \
	device/samsung/exynos4/lib/mali_ump/libion.so:system/lib/libion.so \
	device/samsung/exynos4/lib/mali_ump/libion.so:obj/lib/libion.so
endif

# Init files
PRODUCT_COPY_FILES += \
	device/samsung/smdk4x12/conf/init.smdk4x12.rc:root/init.smdk4x12.rc \
	device/samsung/smdk4x12/conf/init.smdk4x12.usb.rc:root/init.smdk4x12.usb.rc

#add by mch for audio 20170822
PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/audio/audio.sh:/system/etc/audio.sh \
	device/samsung/smdk4x12/audio/tinymix:/system/bin/tinymix \
	device/samsung/smdk4x12/audio/buzzer:/system/bin/buzzer

PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/can/config_can.sh:/system/etc/config_can.sh \
	device/samsung/smdk4x12/can/canconfig:/system/bin/canconfig \
	device/samsung/smdk4x12/can/cansend:/system/bin/cansend \
	device/samsung/smdk4x12/can/candump:/system/bin/candump \
	device/samsung/smdk4x12/can/canecho:/system/bin/canecho \
	device/samsung/smdk4x12/can/cansequence:/system/bin/cansequence

#add by mch for me3630
PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/me3630/libreference-ril.so:system/lib/libreference-ril.so \
        device/samsung/smdk4x12/me3630/init.dhcpcd_ecm:/system/etc/init.dhcpcd_ecm \
        device/samsung/smdk4x12/me3630/init.ecm_down:/system/etc/init.ecm_down \
        device/samsung/smdk4x12/me3630/init.gprs_pppd:/system/etc/init.gprs_pppd \
	device/samsung/smdk4x12/me3630/ip-up-ppp0:/system/etc/ppp/ip-up-ppp0 \
        device/samsung/smdk4x12/me3630/ip-down-ppp0:/system/etc/ppp/ip-down-ppp0 \
	#device/samsung/smdk4x12/me3630/lte-me3630.ko:/data/lte-me3630.ko



#Camera video backgroud effect file.
PRODUCT_COPY_FILES += \
        frameworks/base/data/videos/Sunset.480p.mq.mp4:system/media/video/Sunset.480p.mp4 \
        frameworks/base/data/videos/Sunset.240p.mp4:system/media/video/Sunset.240p.mp4 \
        frameworks/base/data/videos/Disco.480p.mq.mp4:system/media/video/Disco.480p.mp4 \
        frameworks/base/data/videos/Disco.240p.mp4:system/media/video/Disco.240p.mp4 \
        frameworks/base/data/videos/AndroidInSpace.240p.mp4:system/media/video/AndroidInSpace.240p.mp4 \
        frameworks/base/data/videos/AndroidInSpace.480p.mq.mp4:system/media/video/AndroidInSpace.480p.mp4

# For V4L2
ifeq ($(BOARD_USE_V4L2), true)
ifeq ($(BOARD_USE_V4L2_ION), true)
PRODUCT_COPY_FILES += \
	device/samsung/smdk4x12/conf/ueventd.smdk4x12.v4l2ion.rc:root/ueventd.smdk4x12.rc
else
PRODUCT_COPY_FILES += \
	device/samsung/smdk4x12/conf/ueventd.smdk4x12.v4l2.rc:root/ueventd.smdk4x12.rc
endif
else
PRODUCT_COPY_FILES += \
	device/samsung/smdk4x12/conf/ueventd.smdk4x12.rc:root/ueventd.smdk4x12.rc
endif

#yyd- 120112, tmp for Camera.apk
#PRODUCT_COPY_FILES += \
#	device/samsung/smdk4x12/apk/Camera.apk:system/app/Camera.apk
#	device/samsung/smdk4x12/apk/111.apk:system/app/111.apk

#yyd- 120112 add ecompass apk
#PRODUCT_COPY_FILES += \
#	device/samsung/smdk4x12/apk/com.apksoftware.compass.apk:system/app/com.apksoftware.compass.apk

#replace sensor
#PRODUCT_COPY_FILES += \
#       device/samsung/smdk4x12/apk/sensors.smdk4x12.so:system/lib/hw/sensors.smdk4x12.so

#Install Weather
PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/weather/weather_3.0.apk:system/app/weather_3.0.apk
PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/weather/liblocSDK3.so:system/lib/liblocSDK3.so

#Install Tencent Brower
PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/tencent_brower/QQ_brower_HD_for_Pad_2.3.0.116.apk:system/app/QQ_brower_HD_for_Pad_2.3.0.116.apk
PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/tencent_brower/libcodecwrapper.so:system/lib/libcodecwrapper.so
PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/tencent_brower/libmsfboot.so:system/lib/libmsfboot.so
PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/tencent_brower/libtenpay-jni.so:system/lib/libtenpay-jni.so

#Install Tencent Video
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/tencent_video/tencent_video_HD_1.3.0.4112.apk:system/app/tencent_video_HD_1.3.0.4112.apk
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/tencent_video/libexport.so:system/lib/libexport.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/tencent_video/libexport_neon.so:system/lib/libexport_neon.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/tencent_video/libgetproperty.so:system/lib/libgetproperty.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/tencent_video/libsemaphore.so:system/lib/libsemaphore.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/tencent_video/libsta_jni.so:system/lib/libsta_jni.so

#Install sina_weibo
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/sina_weibo/weibo_3.6.0.apk:system/app/weibo_3.6.0.apk
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/sina_weibo/libbsdiffjni.so:system/lib/libbsdiffjni.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/sina_weibo/libencrypt.so:system/lib/libencrypt.so

#Install QQ
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/qq/QQ_for_Pad_1.9.3.apk:system/app/QQ_for_Pad_1.9.3.apk
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/qq/libicu_audio.so:system/lib/libicu_audio.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/qq/libicu_video.so:system/lib/libicu_video.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/qq/libqchameleon.so:system/lib/libqchameleon.so

#Install storm player
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/storm/storm_2.5.52.apk:system/app/storm_2.5.52.apk
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/storm/libbaofengmediascan.so:system/lib/libbaofengmediascan.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/storm/libbhdserver.so:system/lib/libbhdserver.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/storm/libcommon.so:system/lib/libcommon.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/storm/libffmpeg.so:system/lib/libffmpeg.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/storm/libffmpegplugin.so:system/lib/libffmpegplugin.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/storm/libmediainfo.so:system/lib/libmediainfo.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/storm/libsplitter.so:system/lib/libsplitter.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/storm/libstormplayer14-jni.so:system/lib/libstormplayer14-jni.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/storm/libstormplayer16-jni.so:system/lib/libstormplayer16-jni.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/storm/libstormplayer4-jni.so:system/lib/libstormplayer4-jni.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/storm/libstormplayer8-jni.so:system/lib/libstormplayer8-jni.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/storm/libstormplayer9-jni.so:system/lib/libstormplayer9-jni.so

#Install 360 Assistant
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/360_assistant_1.9.160.apk:system/app/360_assistant_1.9.160.apk

#Install UvcWebCam
PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/UvcWebCam/UvcWebCam.apk:system/app/UvcWebCam.apk
PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/UvcWebCam/libImageProc.so:system/lib/libImageProc.so

#Install Chess
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/chess/chess_1.62.apk:system/app/chess_1.62.apk
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/chess/libxiangqi.so:system/lib/libxiangqi.so

#Intall start_super
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/start_super/start_super_1.8.apk:system/app/start_super_1.8.apk
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/start_super/libbspatch.so:system/lib/libbspatch.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/start_super/libcocos2dx-game.so:system/lib/libcocos2dx-game.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/start_super/libprotectClass.so:system/lib/libprotectClass.so

#Install 2048
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/2048/2048.apk:system/app/2048.apk
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/2048/libappJni.so:system/lib/libappJni.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/2048/libbase64encoder_v1_4.so:system/lib/libbase64encoder_v1_4.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/2048/libcocos2dcpp.so:system/lib/libcocos2dcpp.so

#Install xunleikankan
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/xunleikankan/xunleikankan.apk:system/app/xunleikankan.apk
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/xunleikankan/libBaiduMapSDK_v2_3_0.so:system/lib/libBaiduMapSDK_v2_3_0.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/xunleikankan/libjpush.so:system/lib/libjpush.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/xunleikankan/liblocSDK4.so:system/lib/liblocSDK4.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/xunleikankan/libmediaplayer_jni.so:system/lib/libmediaplayer_jni.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/xunleikankan/libmediaserver_jni.so:system/lib/libmediaserver_jni.so
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/xunleikankan/libMMANDKSignature.so:system/lib/libMMANDKSignature.so

#Install ESFileExplorer
PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/ESFileExplorer/ESFileExplorer.apk:system/app/ESFileExplorer.apk
PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/ESFileExplorer/libmyaes.so:system/lib/libmyaes.so
PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/ESFileExplorer/libsapi_so_1.so:system/lib/libsapi_so_1.so

#Install LedTest
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/ledtest/ledtest.apk:system/app/ledtest.apk
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/ledtest/libled.so:system/lib/libled.so

#Install Buzzer
PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/buzzer/buzzertest.apk:system/app/buzzertest.apk
PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/buzzer/libbuzzer.so:system/lib/libbuzzer.so

#Install ADC
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/adc/adctest.apk:system/app/adctest.apk
#PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/apk/topeet/adc/libadc.so:system/lib/libadc.so

ifeq ($(BOARD_USES_FFMPEG), true)
#yujian- 120216 add mediaplayer apk
PRODUCT_COPY_FILES += \
	device/samsung/smdk4x12/apk/MediaPlayer.apk:system/app/MediaPlayer.apk
endif

# Prebuilt kl keymaps
#jmq.disable key layout, will check later
#PRODUCT_COPY_FILES += \
#	device/samsung/smdk4x12/samsung-keypad.kl:system/usr/keylayout/samsung-keypad.kl \
#	device/samsung/smdk4x12/pixcir-i2c-ts_key.kl:system/usr/keylayout/pixcir-i2c-ts_key.kl 
PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/eGalaxTouchScreen.idc:system/usr/idc/eGalaxTouchScreen.idc
# Generated kcm keymaps
#PRODUCT_PACKAGES := \
#	samsung-keypad.kcm

PRODUCT_PACKAGES :=

# Filesystem management tools
PRODUCT_PACKAGES += \
	make_ext4fs \
	setup_fs

# audio
PRODUCT_PACKAGES += \
	audio_policy.smdk4x12 \
	audio.primary.smdk4x12 \
	audio.a2dp.default \
	libaudioutils

# ULP Audio
ifeq ($(USE_ULP_AUDIO),true)
PRODUCT_PACKAGES += \
	libaudiohw \
	MusicULP \
	libsa_jni
endif

# ALP Audio
ifeq ($(BOARD_USE_ALP_AUDIO),true)
PRODUCT_PACKAGES += \
	libOMX.SEC.MP3.Decoder
endif

# Camera
PRODUCT_PACKAGES += \
	camera.smdk4x12 \

# SEC_Camera
ifeq ($(USE_SEC_CAMERA),true)
PRODUCT_PACKAGES += \
	SEC_Camera
endif

# Libs
PRODUCT_PACKAGES += \
	libcamera \
	libstagefrighthw \
	com.android.future.usb.accessory

# Video Editor
PRODUCT_PACKAGES += \
	VideoEditorGoogle

# Misc other modules
PRODUCT_PACKAGES += \
	lights.smdk4x12 \
	hwcomposer.exynos4
#GPS
PRODUCT_PACKAGES += \
       	gps.exynos4

# OpenMAX IL configuration files
PRODUCT_COPY_FILES += \
	device/samsung/smdk4x12/media_profiles.xml:system/etc/media_profiles.xml

# OpenMAX IL modules
PRODUCT_PACKAGES += \
	libSEC_OMX_Core \
	libSEC_OMX_Resourcemanager \
	libOMX.SEC.AVC.Decoder \
	libOMX.SEC.M4V.Decoder \
	libOMX.SEC.M4V.Encoder \
	libOMX.SEC.AVC.Encoder

# hwconvertor modules
PRODUCT_PACKAGES += \
	libhwconverter \

# MFC firmware
PRODUCT_COPY_FILES += \
	device/samsung/exynos4/firmware/mfc_fw.bin:root/vendor/firmware/mfc_fw.bin

# FIMC-IS firmware
PRODUCT_COPY_FILES += \
	device/samsung/exynos4/firmware/fimc_is_fw.bin:root/vendor/firmware/fimc_is_fw.bin \
	device/samsung/exynos4/firmware/setfile.bin:root/vendor/firmware/setfile.bin

# Input device calibration files
#PRODUCT_COPY_FILES += \
#	device/samsung/smdk4x12/s5pc210_ts.idc:system/usr/idc/s5pc210_ts.idc \
#	device/samsung/smdk4x12/pixcir-i2c-ts.idc:system/usr/idc/pixcir-i2c-ts.idc

#add by cym 20130515
PRODUCT_COPY_FILES += \
	device/samsung/smdk4x12/ft5x0x_ts.idc:system/usr/idc/ft5x0x_ts.idc
#end add

#add by mch 20170712
PRODUCT_PACKAGES += \
	cantest

PRODUCT_COPY_FILES += \
	device/samsung/common/libcanjni/canset.sh:system/bin/canset.sh \
	device/samsung/common/libcanjni/canset:system/bin/canset \
#end add

PRODUCT_COPY_FILES += \
	frameworks/base/data/etc/android.hardware.usb.accessory.xml:system/etc/permissions/android.hardware.usb.accessory.xml \
	frameworks/base/data/etc/android.hardware.wifi.xml:system/etc/permissions/android.hardware.wifi.xml \
	frameworks/base/data/etc/android.hardware.wifi.direct.xml:system/etc/permissions/android.hardware.wifi.direct.xml \
	packages/wallpapers/LivePicker/android.software.live_wallpaper.xml:system/etc/permissions/android.software.live_wallpaper.xml

# The OpenGL ES API level that is natively supported by this device.
# This is a 16.16 fixed point number
PRODUCT_PROPERTY_OVERRIDES := \
	ro.opengles.version=131072

PRODUCT_PROPERTY_OVERRIDES += \
	hwui.render_dirty_regions=false

# Set default USB interface
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += \
	persist.sys.usb.config=mass_storage

ifeq ($(BOARD_USES_HIGH_RESOLUTION_LCD),true)
PRODUCT_CHARACTERISTICS := tablet

PRODUCT_COPY_FILES += \
	frameworks/base/data/etc/tablet_core_hardware.xml:system/etc/permissions/tablet_core_hardware.xml

$(call inherit-product, frameworks/base/build/tablet-dalvik-heap.mk)

else
PRODUCT_CHARACTERISTICS := phone

PRODUCT_COPY_FILES += \
	frameworks/base/data/etc/handheld_core_hardware.xml:system/etc/permissions/handheld_core_hardware.xml

$(call inherit-product, frameworks/base/build/phone-hdpi-512-dalvik-heap.mk)

PRODUCT_PROPERTY_OVERRIDES += \
	ro.sf.lcd_density=240

PRODUCT_AAPT_CONFIG := normal hdpi
endif

# we have enough storage space to hold precise GC data
PRODUCT_TAGS += dalvik.gc.type-precise

# NFC
PRODUCT_PACKAGES += \
	libnfc \
	libnfc_jni \
	Nfc \
	Tag \
	libsnfc_fw
	
# NFC	
PRODUCT_PACKAGES += \
	nfc.default

	
# NFC
PRODUCT_COPY_FILES += \
	frameworks/base/data/etc/android.hardware.nfc.xml:system/etc/permissions/android.hardware.nfc.xml

# NFC EXTRAS add-on API
PRODUCT_PACKAGES += \
	com.android.nfc_extras
PRODUCT_COPY_FILES += \
	frameworks/base/nfc-extras/com.android.nfc_extras.xml:system/etc/permissions/com.android.nfc_extras.xml
	
	
# hwconvertor modules
PRODUCT_PACKAGES += \
	libhwconverter \

#add by cym 20130623
  include $(LOCAL_PATH)/../common/cfg_audio/cfg_audio_product_packages.mk
  include $(LOCAL_PATH)/../common/lib3G/3g_product_packages.mk
#  include $(LOCAL_PATH)/../common/libcamera/camera_product_packages.mk

ifeq ($(BOARD_HAVE_GNS7560),true)
  include $(LOCAL_PATH)/../common/libgps/gps_product_packages.mk
endif

ifneq ($(BOARD_HAVE_MPU6050),true)
  include $(LOCAL_PATH)/../common/libsensors_mpu3050/sensors_product_packages.mk
endif

ifeq ($(BOARD_HAVE_MPU6050),true)
  include $(LOCAL_PATH)/../common/libsensors_mpu6050/libsensors_product_packages.mk
endif
ifeq ($(BOARD_HAVE_MTK_MT6620),true)
  include $(LOCAL_PATH)/../common/mt6620/mt6620_product_package.mk
endif

  include $(LOCAL_PATH)/../common/TSC2007/Android_TSC2007.mk

